import "./globals.css";
import '@fontsource/dm-sans';
import React from 'react';

export const metadata = {title: "Oakmont Athletic", description: "Generated by create next app"};
export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                {children}
            </body>
        </html>
    );
}
